### ISSUE TITLE
Support std::time::Duration

### ISSUE THREAD

**Issue by jonhoo** [andrewjstone/ferris#2]
`ferris` currently operates on `time::Duration` from the (deprecated) `time` crate. It would be great if it could instead use the standard `Duration` struct from `std::time`.

**Comment by andrewjstone** [comment]
whoops I accidentally clicked the close button. I agree this would be good. I'm working with a few people on my team learning Rust right now and I might point one of them at this as it's an easy issue. I already have 1 person looking at issue #1, but it's not his top priority. This itself should be a very simple change, and I can probably just do it. It's just nice to see commits from others :)

**Comment by jonhoo** [comment]
I'd also be happy to give some guidance if you're swamped.

**Comment by andrewjstone** [comment]
Thanks Jon. If it's of an immediate need and you want to go ahead and implement that would be nice. If it can wait a few days I or someone on my team will go ahead and do it. It should be very easy. Today is my first day back from vacation, so a bit swamped playing catchup.

**Comment by jonhoo** [comment]
No rush at all. I just added a dependency on `time` and used `time::Duration::from` in the meantime. I'd just like to remove that legacy dependency eventually.

**Comment by andrewjstone** [comment]
Got it. I'll keep it high on my list. I'm very happy to hear  that you are using ferris btw. I'm a big fan of hdrsample, although I haven't gotten a chance to really use it in depth. Been kind of in a different world the last few months, with rust stuff lagging a bit. That's about to change though. May I ask what you are using ferris for?

**Comment by jonhoo** [comment]
Glad to hear you like hdrsample! :)

I'm using `ferris` to track batching timeouts across a number of input channels in a data-flow database research prototype I'm building over at https://github.com/mit-pdos/distributary. It's being used pretty deep in the internals, but if you're curious, the timers appear near https://github.com/mit-pdos/distributary/blob/a8e8a56a644578b6c329f9a6ec9853ba4836710b/src/worker/worker.rs#L197.

**Comment by andrewjstone** [comment]
That project looks awesome. I'll have to give the Soup paper a read.

**Comment by jonhoo** [comment]
There unfortunately isn't a full paper out (yet), but some preliminary work is described here: https://jon.thesquareplanet.com/papers/sosp17src-xylem.pdf

**Comment by andrewjstone** [comment]
I realized that when I clicked on the slide link that I thought was going to be a paper. Thanks for the link.

**Comment by andrewjstone** [comment]
closed by #7
